config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :projects, only: [:index, :create, :update, :edit, :new, :show] do
    resources :metrics, only: [:index], controller: "projects/metrics"
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :index, :destroy ]
    resources :rewards, only: [ :index ] do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :details, to: 'projects/contribution_details#index'
        get :fallback_create, to: 'projects/contributions#create'
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'about_mobile'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides



  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'refuse'
        put 'request_refund'
        put 'trash'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/controllers/admin/financials_controller.rb
class Admin::FinancialsController < Admin::BaseController
  layout 'catarse_bootstrap'
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'

  has_scope :pg_search, :user_name_contains, :financial, :with_state, :by_progress
  has_scope :between_expires_at, using: [ :start_at, :ends_at ], allow_blank: true

  respond_to :html, :csv

  actions :index

  def index
    respond_to do |format|
      format.html {collection}
      format.csv do
        financials = ProjectFinancial.where(project_id: projects.select("id"))

        self.response_body = Enumerator.new do |y|
          financials.copy_to do |line|
            y << line
          end
        end
      end
    end
  end

  protected
  def projects
    apply_scopes(Project).includes(:user).order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, expires_at::date DESC")
  end

  def collection
    @scoped_projects = projects
    @projects ||= @scoped_projects.page(params[:page])
  end
end

app/views/catarse_bootstrap/admin/financials/index.html.slim
= render 'shared/header_big'
.w-row.admin
  h1= @title = t('.title')
  = simple_form_for '', url: admin_financials_path, method: :get do |form|
    .w-row
      .w-col-2.w-col
        = form.input :pg_search, as: :string, label: t('.permalink'), input_html: {value: current_scopes[:search_on_name]}
      .w-col-2.w-col
        = form.input "between_expires_at[start_at]", as: :string, label: t(".between_expires_at"), input_html: {value: params[:between_expires_at] && params[:between_expires_at][:start_at], data: { fixed_mask: '99/99/9999' } }
      .w-col-2.w-col
        = form.input "between_expires_at[ends_at]", as: :string, label: '', input_html: {value: params[:between_expires_at] && params[:between_expires_at][:ends_at], data: { fixed_mask: '99/99/9999' } }
      .w-col-2.w-col
        = form.input :by_progress, as: :string, label: t('.by_progress'), input_html: {value: params[:by_progress]}
      .w-col-2.w-col
        = form.input :user_name_contains, as: :string, label: t('.user'), input_html: {value: params[:user_name_contains]}
      .w-col-2.w-col
        = form.input :with_state, collection: Project.state_names, label: t('admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true

    .w-row
      .w-col-2.w-col
        = form.button :submit, t('admin.filter.submit'), class: 'button medium negative'
      .w-col-2.w-col
        = link_to t('.search_report'), admin_financials_path(params: params,format: :csv)
      .w-col-2.w-col
        p.filtered-number = @scoped_projects.count(:all)
        p.filtered-number-label
          = pluralize_without_number(@scoped_projects.count(:all), t('project_singular'), t('project_plural'))
          '
          = pluralize_without_number @scoped_projects.count(:all), t('found_singular'), t('found_plural')

  = paginate @projects
  - if @projects.empty?
    = t('.no_projects')
  - else
    - @projects.each do |project|
      table.table.fontsize-smallest
        thead.card.card-secondary
          tr
            th style="width: 200px"= t('.name')
            th= t('.user')
            th= t('.goal')
            th= t('.pledged')
            th= t('.total_payment_service_fee')
            th= t('.total_catarse_fee')
            th= t('.repass_value')
            th= t('.expires_at')
            th= t('.reports')
            th= t('.zero_fee')
            th= t('.state')
        tbody
          tr id=project.id
            td= link_to project.name, project_by_slug_path(permalink: project.permalink), target: '_blank'
            td= link_to (project.user.moip_login.blank? ? 'Não preenchido' : project.user.moip_login), user_path(project.user, anchor: :settings), target: '_blank'
            td= project.display_goal
            td= project.display_pledged_with_cents
            td= number_to_currency project.total_payment_service_fee, precision: 2
            - catarse_fee = CatarseSettings[:catarse_fee].to_f * project.pledged
            td
              = number_to_currency catarse_fee, precision: 2
            td
              = number_to_currency ((project.pledged*0.87)), precision: 2
            td
              = project.display_expires_at
            td
              = link_to t('.contribution_report'), admin_reports_contribution_reports_path(project_id: project.id, format: :csv)
            td
              = project.has_blank_service_fee?
            td
              - if project.online?
                span.label.label-online= project.state
              - elsif project.successful?
                span.label.label-success= project.state
              - elsif project.failed? or project.rejected?
                span.label.label-important= project.state
              - elsif project.waiting_funds?
                span.label.label-warning= project.state
              - else
                span.label= project.state
          tr class='detail_tr' id="project_details-#{project.id}"
            td colspan='11'
              table style='border: 1px #ededed solid'
                thead
                  th style='width: 350px'= t('.details.bank_data')
                  th= t('.details.name')
                  th= t('.details.document')
                  th= t('.details.email')
                  th= t('.details.state_inscription')
                  th= t('.details.address')
                  th= t('.details.phone_number')
                  th= t('.details.permalink')
                tbody
                  tr
                    td
                      = project.account.try(:decorate).try(:display_bank_account)
                      br/
                      = project.account.try(:decorate).try(:display_bank_account_owner)
                    td= project.account.try(:decorate).try(:display_name)
                    td= project.account.try(:owner_document)
                    td= project.account.try(:email)
                    td= project.account.try(:state_inscription)
                    td= project.account.try(:decorate).try(:display_address)
                    td= project.account.try(:phone_number)
                    td= link_to project.permalink, project_by_slug_path(permalink: project.permalink), target: '_blank'

  = paginate @projects
= render 'shared/footer_big'