config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :projects, only: [:index, :create, :update, :edit, :new, :show] do
    resources :metrics, only: [:index], controller: "projects/metrics"
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :index, :destroy ]
    resources :rewards, only: [ :index ] do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :details, to: 'projects/contribution_details#index'
        get :fallback_create, to: 'projects/contributions#create'
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'about_mobile'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides



  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'refuse'
        put 'request_refund'
        put 'trash'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route, allow_nil: true


    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/error_groups.rb
module Project::ErrorGroups
  extend ActiveSupport::Concern

  included do
    begin
      ATTR_GROUPS = {
        basics: [:name, :permalink, :category_id, :goal, :online_days],
        project: [ :video_url, :about_html, :budget, :uploaded_image, :headline],
        reward: [:'rewards.size', :'rewards.minimum_value', :'rewards.deliver_at'],
        user_about: [:'user.uploaded_image', :'user.name', :'user.about_html'],
        user_settings: ProjectAccount.attribute_names.map{|attr| ('project_account.' + attr).to_sym} << :account
      }
    rescue Exception => e
      puts "problem while using ErrorGroups concenr:\n '#{e.message}'"
    end

    def error_included_on_group? error_attr, group_name
      Project::ATTR_GROUPS[group_name.to_sym].include?(error_attr)
    end

    def has_errors_for?(field)
      errors.include?(field)
    end
  end
end

app/models/concerns/project/reminders_handler.rb
module Project::RemindersHandler
  extend ActiveSupport::Concern

  included do
    def user_already_in_reminder?(user_id)
      notifications.where(template_name: 'reminder', user_id: user_id).present? ||
      user_in_reminder_queue?(user_id)
    end

    def user_in_reminder_queue?(user_id)
      scheduler_set.any? do |job|
        job_matches?(job, user_id)
      end
    end

    def delete_from_reminder_queue(user_id)
      job = scheduler_set.select do |job|
        job_matches?(job, user_id)
      end

      job.each(&:delete)
    end

    def job_matches?(job, user_id)
      job['class'] == 'ReminderProjectWorker' &&
      job.args[0] == user_id &&
      job.args[1] == self.id
    end

    def scheduler_set
      @queue_set ||= Sidekiq::ScheduledSet.new
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  protected
  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contribution_details_controller.rb
class Projects::ContributionDetailsController < ApplicationController
  has_scope :was_confirmed, type: :boolean
  has_scope :pending, type: :boolean
  has_scope :page, default: 1

  def index
    render collection
  end

  def collection
    @contributions ||= apply_scopes(parent.contribution_details).available_to_display.order("created_at DESC").per(10)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: 10)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.referral_link = referral_link
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  protected
  def load_rewards
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/metrics_controller.rb
class Projects::MetricsController < ApplicationController
  after_filter :verify_authorized
  respond_to :html
  layout false

  def index
    authorize parent, :update?

    @metrics ||= {
      address_state: collection.total_by_address_state,
      confirmed: collection.total_confirmed_by_day,
      confirmed_amount_by_day: collection.total_confirmed_amount_by_day
    }

    respond_with @metrics
  end

  protected

  def collection
    @contributions ||= parent.contribution_details
  end

  def parent
    @project ||= Project.find params[:project_id]
  end

end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  after_filter :verify_authorized, except: %i[index destroy]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @posts ||= policy_scope(parent.posts).ordered
    render @posts.page(params[:page]).per(3)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects/reminders_controller.rb
class Projects::RemindersController < ApplicationController
  before_filter :authenticate_user!

  def create
    unless current_user.has_valid_contribution_for_project?(params[:id]) && project.user_already_in_reminder?(current_user.id)
      reminder_at = project.expires_at - 48.hours
      ReminderProjectWorker.perform_at(reminder_at, current_user.id, project.id)
    end
    flash[:notice] = t('projects.reminder.ok')
    redirect_to project_by_slug_path(project.permalink)
  end

  def destroy
    project.notifications.where(template_name: 'reminder', user_id: current_user.id).destroy_all
    project.delete_from_reminder_queue(current_user.id)

    redirect_to project_by_slug_path(project.permalink)
  end


  protected

  def project
    @project ||= Project.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: %i[index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit show]

  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    index! do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
        projects_for_home
      end
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new params[:project].merge(user: current_user, referral_link: referral_link)
    authorize @project
    if @project.save
      redirect_to edit_project_path(@project, anchor: 'home')
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis
  end

  def publish
    authorize resource
    resource_action :push_to_online
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.attributes = permitted_params

    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  def about_mobile
    resource
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?
    @budget = resource.budgets.build

    resource.build_account unless resource.account
  end

  def resource_action action_name
    if resource.send(action_name)
      if referral_link.present?
        resource.update_attribute :referral_link, referral_link
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      redirect_to edit_project_path(@project, anchor: 'home')
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    @projects = apply_scopes(Project.visible.order_status)
      .most_recent_first
      .includes(:project_total, :user, :category)
      .page(params[:page]).per(18)

    render partial: 'projects/card',
      collection: @projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects_for_home
    @recommends = ProjectsForHome.recommends.includes(:project_total, :user)
    @projects_near = Project.with_state('online').near_of(current_user.address_state).order("random()").limit(3).includes(:project_total, :user) if current_user
    @expiring = ProjectsForHome.expiring.includes(:project_total, :user)
    @recent   = ProjectsForHome.recents.includes(:project_total, :user)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/projects/_budget.html.slim
- if @project.budget.present?
  p.fontsize-large.fontweight-semibold
    | Orçamento
  p.fontsize-base
    = @project.budget.try(:html_safe)
  /- if @project.budgets.present?
    = pie_chart @project.budgets.pluck(:name, :value), id: "budget-chart"

app/views/catarse_bootstrap/projects/_edit_action.html.slim
- if policy(@project).update? && @project.published?
  .w-row.u-marginbottom-20
    .w-col.w-col-4
      = link_to text, edit_project_path(@project, anchor: anchor), class: 'btn btn-edit btn-small'
    .w-col.w-col-8
  .u-marginbottom-30

app/views/catarse_bootstrap/projects/_link_fields.html.slim
#links.w-row
    - if f.object.persisted?
      .link
        .w-col.w-col-10.w-col-small-10.w-col-tiny-10
          = f.input_field :link, as: :string, class: 'w-input text-field'
        .w-col.w-col-2.w-col-small-2.w-col-tiny-2
          = link_to_remove_association "", f, class: 'btn btn-small btn-terciary fa fa-lg fa-trash btn-no-border', wrapper_class: 'link' 
    - else
      .link
        .w-col.w-col-10.w-col-small-10.w-col-tiny-10
          = f.input_field :link, as: :string, class: 'w-input text-field positive'
        .w-col.w-col-2.w-col-small-2.w-col-tiny-2
          = link_to_remove_association "", f, class: 'btn btn-small btn-terciary fa fa-lg fa-trash btn-no-border', wrapper_class: 'link' 

app/views/catarse_bootstrap/projects/_mobile_video.html.slim
.w-hidden-main.w-hidden-medium.project-video-div-mobile
  .w-container
    .w-embed.w-video.project-video style=("padding-top: 56.20608899297424%;") 
      iframe.embedly-embed allowfullscreen="" frameborder="0" scrolling="no" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F9V8W7IWv4vU%3Ffeature%3Doembed&amp;url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9V8W7IWv4vU&amp;image=http%3A%2F%2Fi1.ytimg.com%2Fvi%2F9V8W7IWv4vU%2Fhqdefault.jpg&amp;key=c4e54deccf4d4ec997a64902e9a30300&amp;type=text%2Fhtml&amp;schema=youtube" 
      iframe.embedly-embed src="#{@project.display_video_embed_url}"  width="100%" height="379" frameborder="0" allowFullScreen
.w-hidden-main.w-hidden-medium.project-about-highlight
  .w-container
    p.w-hidden-main.w-hidden-medium.fontsize-small = @project.headline
    = link_to t('.read_more'), about_mobile_project_path(@project), class: "alt-link fontsize-small"
.w-container.w-hidden-main.w-hidden-medium.project-stats
  .w-row.w-hidden-main.w-hidden-medium
    .w-col.w-col-3.w-col-small-3.w-col-tiny-3.fontweight-semibold
      .fontsize-largest = @project.total_contributions
      .fontsize-smaller.lineheight-tighter = t('projects.project_main.sidebar.contributions')
    .w-col.w-col-6.w-col-small-6.w-col-tiny-6.fontweight-semibold
      .fontsize-largest = @project.display_pledged
      .fontsize-smaller.lineheight-tighter = t('projects.project_main.sidebar.goal', total: @project.display_goal)
    .w-col.w-col-3.w-col-small-3.w-col-tiny-3.fontweight-semibold
      .fontsize-largest = @project.remaining_days
      .fontsize-smaller.lineheight-tighter  #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}

app/views/catarse_bootstrap/projects/_project_about.html.slim
- if resource.video_url.present?
  .w-embed.w-video.project-video
    iframe itemprop="video" src="#{@project.display_video_embed_url}" class="embedly-embed" width="100%" height="379" frameborder="0" allowFullScreen

.project-share.u-marginbottom-30.w-row
  .w-col.w-col-3
    #facebook_share.img-share = render_facebook_share title: @project.name, href: project_by_slug_url(@project.permalink, locale: I18n.locale, ref: 'facebook')
  .w-col.w-col-3
    #twitter_share.img-share = render_twitter(url: project_by_slug_url(permalink: @project.permalink, ref: 'twitter'), title: @project.name)
  .w-col.w-col-3
    = link_to t('.embed'), '#embed', id: 'embed_link', class: 'link-hidden fontsize-small fontcolor-secondary'
  .w-col.w-col-3
    - if @project.online?
      - if user_signed_in? && @project.user_already_in_reminder?(current_user.id)
        .fontsize-small
          = link_to t('.deactive_btn'), reminder_project_path(@project), class: 'fa fa-clock-o link-hidden-success u-right', method: :delete, id: 'reminder'
      - else
        .fontsize-small
          = link_to t('.active_btn'), reminder_project_path(@project), class: 'fa fa-clock-o link-hidden u-right fontcolor-secondary', id: 'reminder'

#project_embed.w-hidden data-path=embed_panel_project_path(@project)

.project-about
  .fontsize-large.u-marginbottom-30[itemprop="name"] = @project.headline.try(:strip)
  .no-mobile
    .fontsize-base[itemprop="about"]
      = @project.about_html.try(:html_safe)
.project-about
  .no-mobile
    .fontsize-base[itemprop="budget"]
      = render 'budget'

app/views/catarse_bootstrap/projects/_project_embed.html.slim
- box_width = "300px"
- box_height = "314px"

.w-row.card.card-terciary.u-marginbottom-20
  .w-col.w-col-6.w-sub-col
    .fontweight-semibold.u-marginbottom-20.fontsize-small= t('.insert')
    .w-form
      = text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '" scrolling="no"></iframe>', class: 'w-input text-field ', readonly: true, rows: 5
  .w-col.w-col-6
    iframe frameborder="0" height=box_height src=embed_project_url(@project) width=box_width scrolling="no"

app/views/catarse_bootstrap/projects/_project_header.html.slim
#project-header.page-header.u-text-center[data-stats=@project.to_analytics_json]
  .w-container
    h1.fontsize-larger.fontweight-semibold.project-name[itemprop="name"] = @project.name
    h2.fontsize-base.lineheight-looser[itemprop="author"]
      = t('projects.index.box.by')
      |&nbsp;
      = @project.user.display_name

app/views/catarse_bootstrap/projects/about_mobile.html.slim
- content_for :title, "#{@project.name} · #{CatarseSettings[:company_name]}"
= render 'shared/header'

.page-header.u-text-center
  .w-container
    .fontsize-larger.fontweight-semibold.project-name = @project.name
    .fontsize-base
      => t('.by')
      a.link-hidden = @project.user.name
.section-one-column
  .w-container.fontsize-base.fontweight-semibold.u-marginbottom-20
    a.alt-link href=project_path(@project)
      strong = t('.back')
  .w-container
    .w-row
      .w-col.w-col-12
        p.fontsize-base[itemprop="about"]
          = @project.about_html.try(:html_safe)
      .w-col.w-col-12
        p.fontsize-base[itemprop="budget"]
          = render 'budget'
  .w-container.fontsize-base.fontweight-semibold
    a.alt-link href=project_path(@project)
      strong= t('.back')
= render 'shared/footer_big'

app/views/catarse_bootstrap/projects/index.html.slim
- content_for :title, t('site.title')
= render 'shared/header_big', overlayer: true

section#hero-home.hero-full.hero-knowmore
  .w-container.u-text-center
    .hero-home-words-content
      .fontsize-megajumbo.u-marginbottom-60.fontweight-semibold
        .w-embed
          .cd-headline.letters.type
            span = t('.banner_before')     
            span.cd-words-wrapper
              - t('.banner_words').each do |index, word|
                - if index == 0 
                  b.is-visible = word
                - else
                  b = word
            span = t('.banner_after')
    w-row
      .w-col.w-col-4
      .w-col.w-col-4
        a.btn.btn-large.u-marginbottom-10 href="#{hello_path(ref: 'home_banner')}" Saiba mais
      .w-col.w-col-4

section#projects
  - if current_user && @projects_near.present?
    article.section.u-marginbottom-40
      .w-container
        .w-row.u-marginbottom-30
          .w-col.w-col-10.w-col-small-6.w-col-tiny-6
            .fontsize-large.lineheight-looser
              = t('.near_you')
          .w-col.w-col-2.w-col-small-6.w-col-tiny-6
            = link_to t('.see_all'), explore_path(ref: 'home_near', anchor: "near_of/" ) + current_user.address_state, class: 'btn btn-small btn-terciary'
        .w-row
          == render_projects @projects_near, 'home_near', { wrapper_class: 'w-col w-col-4' }

  article.section.w-container
    .w-row.u-marginbottom-30
      .w-col.w-col-10.w-col-small-6.w-col-tiny-6
        .fontsize-large.lineheight-looser
          = t('.recommended')
      .w-col.w-col-2.w-col-small-6.w-col-tiny-6
        = link_to t('.see_all'), explore_path(ref: :home_recommended, anchor: :recommended), class: 'btn btn-small btn-terciary'
    .w-row
      == render_projects @recommends, 'home_recommended', { wrapper_class: 'w-col w-col-4' }

  article.section.w-container
    .w-row.u-marginbottom-30
      .w-col.w-col-10.w-col-small-6.w-col-tiny-6
        .fontsize-large.lineheight-looser
          = t('.expiring')
      .w-col.w-col-2.w-col-small-6.w-col-tiny-6
        = link_to t('.see_all'), explore_path(ref: :home_expiring, anchor: :expiring), class: 'btn btn-small btn-terciary'
    .w-row
      == render_projects @expiring, 'home_expiring', { wrapper_class: 'w-col w-col-4' }

  article.section.recent-projects.w-container
    .w-row.u-marginbottom-30
      .w-col.w-col-10.w-col-small-6.w-col-tiny-6
        .fontsize-large.lineheight-looser
          = t('.recents')
      .w-col.w-col-2.w-col-small-6.w-col-tiny-6
        = link_to t('.see_all'), explore_path(ref: :home_recent, anchor: :recent), class: 'btn btn-small btn-terciary'
    .w-row
      == render_projects @recent, 'home_recent', { wrapper_class: 'w-col w-col-4' }

section#blog.section-large.bg-gray.before-footer
  .w-container
    .u-text-center
      = link_to CatarseSettings[:blog_url], target: :blank do
        = image_tag "icon-blog.png", class: "u-marginbottom-10"
      .fontsize-large.u-marginbottom-60.text-success
        = link_to t('.blog'), CatarseSettings[:blog_url], target: '__blank', class: 'link-hidden-success'
    .w-row
      - (Blog.fetch_last_posts rescue [])[0..2].each do |post|
        .w-col.w-col-4.col-blog-post
          = link_to post.url, target: '__blank', class: 'link-hidden fontweight-semibold fontsize-base u-marginbottom-10' do
            /span.fontweight-semibold.fontsize-base.u-marginbottom-10
            = truncate(post.title, length: 80)
          .fontsize-smaller.fontcolor-secondary.u-margintop-10
            /= link_to post.url, target: '__blank', class: 'fontsize-smaller fontcolor-secondary ' do
            /span.fontsize-smaller.fontcolor-secondary
          = truncate(post.summary, length: 130).html_safe    


= render 'shared/footer_big'