config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :projects, only: [:index, :create, :update, :edit, :new, :show] do
    resources :metrics, only: [:index], controller: "projects/metrics"
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :index, :destroy ]
    resources :rewards, only: [ :index ] do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :details, to: 'projects/contribution_details#index'
        get :fallback_create, to: 'projects/contributions#create'
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'about_mobile'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides



  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'refuse'
        put 'request_refund'
        put 'trash'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route, allow_nil: true


    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/error_groups.rb
module Project::ErrorGroups
  extend ActiveSupport::Concern

  included do
    begin
      ATTR_GROUPS = {
        basics: [:name, :permalink, :category_id, :goal, :online_days],
        project: [ :video_url, :about_html, :budget, :uploaded_image, :headline],
        reward: [:'rewards.size', :'rewards.minimum_value', :'rewards.deliver_at'],
        user_about: [:'user.uploaded_image', :'user.name', :'user.about_html'],
        user_settings: ProjectAccount.attribute_names.map{|attr| ('project_account.' + attr).to_sym} << :account
      }
    rescue Exception => e
      puts "problem while using ErrorGroups concenr:\n '#{e.message}'"
    end

    def error_included_on_group? error_attr, group_name
      Project::ATTR_GROUPS[group_name.to_sym].include?(error_attr)
    end

    def has_errors_for?(field)
      errors.include?(field)
    end
  end
end

app/models/concerns/project/reminders_handler.rb
module Project::RemindersHandler
  extend ActiveSupport::Concern

  included do
    def user_already_in_reminder?(user_id)
      notifications.where(template_name: 'reminder', user_id: user_id).present? ||
      user_in_reminder_queue?(user_id)
    end

    def user_in_reminder_queue?(user_id)
      scheduler_set.any? do |job|
        job_matches?(job, user_id)
      end
    end

    def delete_from_reminder_queue(user_id)
      job = scheduler_set.select do |job|
        job_matches?(job, user_id)
      end

      job.each(&:delete)
    end

    def job_matches?(job, user_id)
      job['class'] == 'ReminderProjectWorker' &&
      job.args[0] == user_id &&
      job.args[1] == self.id
    end

    def scheduler_set
      @queue_set ||= Sidekiq::ScheduledSet.new
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  protected
  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contribution_details_controller.rb
class Projects::ContributionDetailsController < ApplicationController
  has_scope :was_confirmed, type: :boolean
  has_scope :pending, type: :boolean
  has_scope :page, default: 1

  def index
    render collection
  end

  def collection
    @contributions ||= apply_scopes(parent.contribution_details).available_to_display.order("created_at DESC").per(10)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: 10)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.referral_link = referral_link
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  protected
  def load_rewards
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/metrics_controller.rb
class Projects::MetricsController < ApplicationController
  after_filter :verify_authorized
  respond_to :html
  layout false

  def index
    authorize parent, :update?

    @metrics ||= {
      address_state: collection.total_by_address_state,
      confirmed: collection.total_confirmed_by_day,
      confirmed_amount_by_day: collection.total_confirmed_amount_by_day
    }

    respond_with @metrics
  end

  protected

  def collection
    @contributions ||= parent.contribution_details
  end

  def parent
    @project ||= Project.find params[:project_id]
  end

end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  after_filter :verify_authorized, except: %i[index destroy]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @posts ||= policy_scope(parent.posts).ordered
    render @posts.page(params[:page]).per(3)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects/reminders_controller.rb
class Projects::RemindersController < ApplicationController
  before_filter :authenticate_user!

  def create
    unless current_user.has_valid_contribution_for_project?(params[:id]) && project.user_already_in_reminder?(current_user.id)
      reminder_at = project.expires_at - 48.hours
      ReminderProjectWorker.perform_at(reminder_at, current_user.id, project.id)
    end
    flash[:notice] = t('projects.reminder.ok')
    redirect_to project_by_slug_path(project.permalink)
  end

  def destroy
    project.notifications.where(template_name: 'reminder', user_id: current_user.id).destroy_all
    project.delete_from_reminder_queue(current_user.id)

    redirect_to project_by_slug_path(project.permalink)
  end


  protected

  def project
    @project ||= Project.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: %i[index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit show]

  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    index! do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
        projects_for_home
      end
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new params[:project].merge(user: current_user, referral_link: referral_link)
    authorize @project
    if @project.save
      redirect_to edit_project_path(@project, anchor: 'home')
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis
  end

  def publish
    authorize resource
    resource_action :push_to_online
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.attributes = permitted_params

    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  def about_mobile
    resource
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?
    @budget = resource.budgets.build

    resource.build_account unless resource.account
  end

  def resource_action action_name
    if resource.send(action_name)
      if referral_link.present?
        resource.update_attribute :referral_link, referral_link
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      redirect_to edit_project_path(@project, anchor: 'home')
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    @projects = apply_scopes(Project.visible.order_status)
      .most_recent_first
      .includes(:project_total, :user, :category)
      .page(params[:page]).per(18)

    render partial: 'projects/card',
      collection: @projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects_for_home
    @recommends = ProjectsForHome.recommends.includes(:project_total, :user)
    @projects_near = Project.with_state('online').near_of(current_user.address_state).order("random()").limit(3).includes(:project_total, :user) if current_user
    @expiring = ProjectsForHome.expiring.includes(:project_total, :user)
    @recent   = ProjectsForHome.recents.includes(:project_total, :user)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/admin/projects/index.html.slim
= render 'shared/header_big'
.w-row.admin.use-sort
  h1.fontsize-largest
    = @title = t('admin.management.title')
    ' :
    = @total_projects
    '
    = t('admin.management.total')

  h3 = t('admin.filter.title')
  = simple_form_for '', url: admin_projects_path, method: :get do |form|
    .w-row
      = form.input :order_by, as: :hidden, input_html: {value: params[:order_by], class: 'w-input text-field'}
      .w-col-3.w-col
        = form.input :pg_search, as: :string, label: t('admin.filter.pg_search'), input_html: {value: params[:pg_search], class: 'w-input text-field'}
      .w-col-3.w-col
        = form.input :user_name_contains, as: :string, label: t('admin.filter.user_name_contains'), input_html: {value: params[:user_name_contains], class: 'w-input text-field'}
      .w-col-2.w-col
        = form.input :by_user_email, as: :string, label: t('.by_user_email'), input_html: {value: params[:by_user_email], class: 'w-input text-field'}
      .w-col-2.w-col
        = form.input :with_state, collection: Project.state_names, label: t('admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true, input_html: { class: 'w-input text-field' }
    .w-row
      - [:between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between].each_with_index do |between_field, index|
        - mask = (between_field == :goal_between ? nil : '99/99/9999')
        - if index % 3 == 0
          .w-row
        .w-col-2.w-col
          = form.input "#{between_field}[start_at]", as: :string, label: t(".#{between_field}"), input_html: {value: params[between_field] && params[between_field][:start_at], data: { fixed_mask: mask } , class: 'w-input text-field'}
        .w-col-2.no-label.w-col
          = form.input "#{between_field}[ends_at]", as: :string, label: false, input_html: { value: params[between_field] && params[between_field][:ends_at], data: { fixed_mask: mask } , class: 'w-input text-field'}

      .w-col-2.no-label.w-col
        = form.button :submit, t('admin.filter.submit'), class: 'btn btn-medium'

    .w-row
      .w-col-2.w-col-offset-10.w-col
        .fontsize-largest = @scoped_projects.count(:all)
        .fontsize-base
          = pluralize_without_number(@scoped_projects.count(:all), t('project_singular'), t('project_plural'))
          '
          = pluralize_without_number @scoped_projects.count(:all), t('found_singular'), t('found_plural')


  = paginate @projects
  - if @scoped_projects.count(:all) < 1
    = t('.no_projects')
  - else
    table.table.fontsize-smallest
      thead.card.card-secondary
        tr
          th.w-col-2.w-col= t('admin.table.name')
          th.w-col-1.w-col= t('admin.table.category')
          th.w-col-1.w-col
            a data-sort="goal" href='#'= t('.goal')
            span.sort-order
          th.w-col-1.w-col
            a data-sort="project_totals.progress" href='#'= t('.pledged')
            span.sort-order
          th.w-col-1.w-col
            a data-sort="project_totals.total_contributions" href='#'= t('.total_contributions')
            span.sort-order
          th.w-col-1.w-col= t('admin.table.recommended')
          th.w-col-1.w-col
            a data-sort="online_date" href='#'= t('.online_date')
            span.sort-order
          th.w-col-1.w-col
            a data-sort="projects.expires_at" href='#'= t('.expires_at')
            span.sort-order
          th.w-col-1.w-col
            a data-sort="updated_at" href='#'= t('.last_modification')
            span.sort-order
          th.w-col-1.w-col= t('admin.table.state')
          th.w-col-1.w-col
      tbody
        - @projects.includes(:category).each do |project|
          tr id=project.id class=cycle("card", "card card-secondary")
            td.w-col-2.w-col= link_to project.name, project_by_slug_path(permalink: project.permalink)
            td.w-col-1.w-col= project.category
            td.w-col-1.w-col= best_in_place [:admin, project], :goal, method: :put, type: :input, display_as: :display_goal
            td.w-col-1.w-col= "#{project.display_pledged_with_cents} (#{project.progress}%)"
            td.w-col-1.w-col= project.total_contributions
            td.w-col-1.w-col= best_in_place [:admin, project], :recommended, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
            td.w-col-1.w-col= project.online_date.strftime('%d/%m/%Y') if project.online_date
            td.w-col-1.w-col= project.display_expires_at
            td.w-col-1.w-col= project.updated_at.strftime('%d/%m/%Y')
            td.w-col-1.w-col
              .w-dropdown-toggle.dropdown-toggle.project-admin-menu
                - if project.online?
                    span.label.label-online= project.state
                - elsif project.successful?
                  span.label.label-success= project.state
                - elsif project.failed? or project.rejected?
                  span.label.label-important= project.state
                - elsif project.waiting_funds?
                  span.label.label-warning= project.state
                - else
                  span.label= project.state
              nav.w-dropdown-list.dropdown-list.user-menu
                - if project.can_push_to_online?
                  li
                    = link_to push_to_online_admin_project_path(project), class: 'w-dropdown-link dropdown-link fontsize-smaller', method: :put do
                      = t('admin.table.put_online')
                - if project.can_approve?
                  li
                    = link_to approve_admin_project_path(project), class: 'w-dropdown-link dropdown-link fontsize-smaller', method: :put do
                      = t('admin.table.approve')

                - if project.can_reject?
                  li
                    = link_to reject_admin_project_path(project), class: 'w-dropdown-link dropdown-link fontsize-smaller', method: :put  do
                      = t('admin.table.reject')

                - if project.can_push_to_draft?
                  li
                    = link_to  push_to_draft_admin_project_path(project), class: 'w-dropdown-link dropdown-link fontsize-smaller', method: :put  do
                      = t('admin.table.send_to_draft')
                - if project.can_push_to_trash?
                  li
                    = link_to  push_to_trash_admin_project_path(project),class: 'w-dropdown-link dropdown-link fontsize-smaller', data:{ confirm: t('admin.table.confirmation')}, method: :put  do
                      = t('admin.table.send_to_trash')


  = paginate @projects
= render 'shared/footer_big'